---
- name: Install Nginx Web Server on Debian Family
  hosts: web
  become: yes


  tasks:
  - name: Install Nginx Web Server on Debian Family
    apt: name=nginx update_cache=yes
  - name: restart nginx
    service: name=nginx state=restarted
